version: "2"
services:
  server:
    build: .
    container_name: DUMMY
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./logs:/opt/app/logs
    links:
      - db
    depends_on:
      - db
  db:
    image: "mongo"
    container_name: MONGODB
    restart: always
    volumes:
      - ./data:/data/db
      - ./csv:/home
    ports:
      - "27018:27017"
